/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatPanel: typeof import('./components/ChatPanel.vue')['default']
    CrudPage: typeof import('./components/CrudPage.vue')['default']
    DetectionPanel: typeof import('./components/panels/DetectionPanel.vue')['default']
    DeviceConfigDialog: typeof import('./components/DeviceConfigDialog.vue')['default']
    DeviceDialog: typeof import('./components/DeviceDialog.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    ModelDialog: typeof import('./components/ModelDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TargetListView: typeof import('./components/panels/TargetListView.vue')['default']
    ThemePicker: typeof import('./components/ThemePicker.vue')['default']
    ThreatPanelView: typeof import('./components/panels/ThreatPanelView.vue')['default']
  }
}
